name: flutter_amplify_sdk
description: An Amplify interoperate library for Flutter application development
version: 0.0.1
homepage: https://github.com/extremevn/famplify

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: vn.com.extremevn.flutter_amplify_sdk
        pluginClass: FlutterAmplifySdkPlugin
      ios:
        pluginClass: FlutterAmplifySdkPlugin